require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_families", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductFamily. As you add validations to ProductFamily, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductFamily.create! valid_attributes
      get product_families_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_family = ProductFamily.create! valid_attributes
      get product_family_url(product_family)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_family_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product_family = ProductFamily.create! valid_attributes
      get edit_product_family_url(product_family)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductFamily" do
        expect {
          post product_families_url, params: { product_family: valid_attributes }
        }.to change(ProductFamily, :count).by(1)
      end

      it "redirects to the created product_family" do
        post product_families_url, params: { product_family: valid_attributes }
        expect(response).to redirect_to(product_family_url(ProductFamily.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductFamily" do
        expect {
          post product_families_url, params: { product_family: invalid_attributes }
        }.to change(ProductFamily, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_families_url, params: { product_family: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested product_family" do
        product_family = ProductFamily.create! valid_attributes
        patch product_family_url(product_family), params: { product_family: new_attributes }
        product_family.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the product_family" do
        product_family = ProductFamily.create! valid_attributes
        patch product_family_url(product_family), params: { product_family: new_attributes }
        product_family.reload
        expect(response).to redirect_to(product_family_url(product_family))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_family = ProductFamily.create! valid_attributes
        patch product_family_url(product_family), params: { product_family: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_family" do
      product_family = ProductFamily.create! valid_attributes
      expect {
        delete product_family_url(product_family)
      }.to change(ProductFamily, :count).by(-1)
    end

    it "redirects to the product_families list" do
      product_family = ProductFamily.create! valid_attributes
      delete product_family_url(product_family)
      expect(response).to redirect_to(product_families_url)
    end
  end
end
