require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/working_hours", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WorkingHour. As you add validations to WorkingHour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WorkingHour.create! valid_attributes
      get working_hours_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      working_hour = WorkingHour.create! valid_attributes
      get working_hour_url(working_hour)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_working_hour_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      working_hour = WorkingHour.create! valid_attributes
      get edit_working_hour_url(working_hour)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WorkingHour" do
        expect {
          post working_hours_url, params: { working_hour: valid_attributes }
        }.to change(WorkingHour, :count).by(1)
      end

      it "redirects to the created working_hour" do
        post working_hours_url, params: { working_hour: valid_attributes }
        expect(response).to redirect_to(working_hour_url(WorkingHour.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WorkingHour" do
        expect {
          post working_hours_url, params: { working_hour: invalid_attributes }
        }.to change(WorkingHour, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post working_hours_url, params: { working_hour: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested working_hour" do
        working_hour = WorkingHour.create! valid_attributes
        patch working_hour_url(working_hour), params: { working_hour: new_attributes }
        working_hour.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the working_hour" do
        working_hour = WorkingHour.create! valid_attributes
        patch working_hour_url(working_hour), params: { working_hour: new_attributes }
        working_hour.reload
        expect(response).to redirect_to(working_hour_url(working_hour))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        working_hour = WorkingHour.create! valid_attributes
        patch working_hour_url(working_hour), params: { working_hour: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested working_hour" do
      working_hour = WorkingHour.create! valid_attributes
      expect {
        delete working_hour_url(working_hour)
      }.to change(WorkingHour, :count).by(-1)
    end

    it "redirects to the working_hours list" do
      working_hour = WorkingHour.create! valid_attributes
      delete working_hour_url(working_hour)
      expect(response).to redirect_to(working_hours_url)
    end
  end
end
